### PR TITLE
스페이스 독자용 익명 프로필 DB 설계

### PR DESCRIPTION
**Pull request by robin-maki**
댓글 쓰는 시점에 멤버인지 체크 -> 익명 프로필 upsert(create시 프로필도 생성) -> 댓글에 프로필 연결
플로우로 진행될 거 같아요

### CODE REVIEW

**Comment by robin-maki** [comment]
Current dependencies on/for this PR:
* main
  * **PR #211** <a href="https://app.graphite.dev/github/pr/penxle/penxle/211" target="_blank">Graphite</a> 
    * **PR #196** <a href="https://app.graphite.dev/github/pr/penxle/penxle/196" target="_blank">Graphite</a> 
      * **PR #202** <a href="https://app.graphite.dev/github/pr/penxle/penxle/202" target="_blank">Graphite</a> 
        * **PR #205** <a href="https://app.graphite.dev/github/pr/penxle/penxle/205" target="_blank">Graphite</a> 
          * **PR #209** <a href="https://app.graphite.dev/github/pr/penxle/penxle/209" target="_blank">Graphite</a> 
            * **PR #215** <a href="https://app.graphite.dev/github/pr/penxle/penxle/215" target="_blank">Graphite</a>  👈
          * **PR #204** <a href="https://app.graphite.dev/github/pr/penxle/penxle/204" target="_blank">Graphite</a> 
            * **PR #207** <a href="https://app.graphite.dev/github/pr/penxle/penxle/207" target="_blank">Graphite</a> 
    * **PR #192** <a href="https://app.graphite.dev/github/pr/penxle/penxle/192" target="_blank">Graphite</a> 
      * **PR #193** <a href="https://app.graphite.dev/github/pr/penxle/penxle/193" target="_blank">Graphite</a> 
        * **PR #198** <a href="https://app.graphite.dev/github/pr/penxle/penxle/198" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/215?utm_source=stack-comment).

**Comment by robin-maki** [comment]
Current dependencies on/for this PR:
* main
  * **PR #211** <a href="https://app.graphite.dev/github/pr/penxle/penxle/211" target="_blank">Graphite</a> 
    * **PR #196** <a href="https://app.graphite.dev/github/pr/penxle/penxle/196" target="_blank">Graphite</a> 
      * **PR #202** <a href="https://app.graphite.dev/github/pr/penxle/penxle/202" target="_blank">Graphite</a> 
        * **PR #205** <a href="https://app.graphite.dev/github/pr/penxle/penxle/205" target="_blank">Graphite</a> 
          * **PR #209** <a href="https://app.graphite.dev/github/pr/penxle/penxle/209" target="_blank">Graphite</a> 
            * **PR #215** <a href="https://app.graphite.dev/github/pr/penxle/penxle/215" target="_blank">Graphite</a>  👈
          * **PR #204** <a href="https://app.graphite.dev/github/pr/penxle/penxle/204" target="_blank">Graphite</a> 
            * **PR #207** <a href="https://app.graphite.dev/github/pr/penxle/penxle/207" target="_blank">Graphite</a> 
    * **PR #192** <a href="https://app.graphite.dev/github/pr/penxle/penxle/192" target="_blank">Graphite</a> 
      * **PR #193** <a href="https://app.graphite.dev/github/pr/penxle/penxle/193" target="_blank">Graphite</a> 
        * **PR #198** <a href="https://app.graphite.dev/github/pr/penxle/penxle/198" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/penxle/penxle/215?utm_source=stack-comment).

**Comment by robin-maki** [comment]
댓글이 출시 이후로 빠지니까 이거 별로 급하지 않을 거 같아요

**Comment by devunt** [comment]
> 댓글이 출시 이후로 빠지니까 이거 별로 급하지 않을 거 같아요

그럴 거 같기도...

**Review by devunt — APPROVED** [review]

**Pull request merged**
